version: 2.0
orbs:
  node: circleci/node@4.7.0
  # aws-cli: circleci/aws-cli@3.1.1
  # aws-s3: circleci/aws-s3@3.0.0
executors:
  docker-node-executor:
    docker:
      - image: cimg/node:14.0.0
master_only: &master_only
  filters:
    branches:
      only:
        - master
dev_only: &dev_only
  filters:
    branches:
      only:
        - dev
jobs:
  build:
    executor: docker-node-executor
    steps:
      - checkout
      - run:
          name: build
          command: |
            npm install
workflows:
  version: 2
  build_test: # this can be any name you choose
    jobs:
      - build:
         <<: *dev
          # filters:
          #   branches:
          #     only: master
